#!/bin/bash

# Security Infrastructure Scan - Combined
# Phase 4: Security Infrastructure Testing

set -e

SCRIPT_DIR="$(dirname "$0")"
SECURITY_TARGET="${SECURITY_TARGET:-http://127.0.0.1:5173}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_DIR="$SCRIPT_DIR/reports"
REPORT_FILE="$REPORT_DIR/infra-report-${TIMESTAMP}.md"

mkdir -p "$REPORT_DIR"

echo "=== Security Infrastructure Scan - Combined ==="
echo "Target: $SECURITY_TARGET"
echo "Timestamp: $TIMESTAMP"
echo ""

# Track results
NMAP_SUCCESS=false
GOBUSTER_SUCCESS=false
TOTAL_WARNINGS=0
TOTAL_CRITICAL=0

# Function to run nmap scan
run_nmap() {
    echo "--- Phase 1: Nmap Scan ---"
    if command -v nmap &> /dev/null; then
        bash "$SCRIPT_DIR/nmap/nmap-scan.sh"
        NMAP_SUCCESS=true
    else
        echo "WARNING: nmap not installed, skipping"
        echo "Install: sudo apt-get install nmap"
    fi
    echo ""
}

# Function to run gobuster scan
run_gobuster() {
    echo "--- Phase 2: Gobuster Scan ---"
    if command -v gobuster &> /dev/null; then
        bash "$SCRIPT_DIR/gobuster/gobuster-scan.sh"
        GOBUSTER_SUCCESS=true
    else
        echo "WARNING: gobuster not installed, skipping"
        echo "Install: go install github.com/OJ/gobuster/v3@latest"
    fi
    echo ""
}

# Function to generate combined report
generate_combined_report() {
    echo "--- Phase 3: Generating Combined Report ---"
    
    LATEST_NMAP=$(ls -t "$REPORT_DIR"/nmap-report-*.md 2>/dev/null | head -1)
    LATEST_GOBUSTER=$(ls -t "$REPORT_DIR"/gobuster-report-*.md 2>/dev/null | head -1)
    
    cat > "$REPORT_FILE" << EOF
# Security Infrastructure Report - Combined

**Date**: $(date)
**Target**: $SECURITY_TARGET
**Scan ID**: $TIMESTAMP

## Executive Summary

- **Nmap Scan**: $([ "$NMAP_SUCCESS" = true ] && echo "COMPLETED" || echo "SKIPPED")
- **Gobuster Scan**: $([ "$GOBUSTER_SUCCESS" = true ] && echo "COMPLETED" || echo "SKIPPED")
- **Total Warnings**: $TOTAL_WARNINGS
- **Total Critical**: $TOTAL_CRITICAL

## Individual Reports

EOF
    
    if [ -n "$LATEST_NMAP" ]; then
        echo "### Nmap Report" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "Full report: \`$LATEST_NMAP\`" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        # Include summary from nmap report
        if [ -f "$LATEST_NMAP" ]; then
            head -30 "$LATEST_NMAP" | tail -20 >> "$REPORT_FILE"
        fi
    fi
    
    if [ -n "$LATEST_GOBUSTER" ]; then
        echo "" >> "$REPORT_FILE"
        echo "### Gobuster Report" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "Full report: \`$LATEST_GOBUSTER\`" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        # Include summary from gobuster report
        if [ -f "$LATEST_GOBUSTER" ]; then
            head -30 "$LATEST_GOBUSTER" | tail -20 >> "$REPORT_FILE"
        fi
    fi
    
    cat >> "$REPORT_FILE" << EOF

## Recommendations

1. Review all warnings and critical findings
2. Close unnecessary ports
3. Restrict access to admin/debug endpoints
4. Remove exposed sensitive files (.env, .git)
5. Implement proper firewall rules
6. Schedule regular security scans

## Next Steps

1. Update baselines after remediation
2. Set up automated scans in CI/CD
3. Monitor for new exposures
4. Document all findings

---
Generated by: Security Infrastructure Scan (Phase 4)
EOF
    
    echo ""
    echo "=== Combined Report generated: $REPORT_FILE ==="
}

# Main execution
run_nmap
run_gobuster
generate_combined_report

echo ""
echo "=== Infrastructure Scan Complete ==="
echo "Report: $REPORT_FILE"
echo "Nmap: $([ "$NMAP_SUCCESS" = true ] && echo "OK" || echo "SKIPPED")"
echo "Gobuster: $([ "$GOBUSTER_SUCCESS" = true ] && echo "OK" || echo "SKIPPED")"
