#!/bin/bash

# Security Infrastructure Scan - Nmap
# Phase 4: Security Infrastructure Testing

set -e

SECURITY_TARGET="${SECURITY_TARGET:-http://127.0.0.1:5173}"
REPORT_DIR="$(dirname "$0")/reports"
BASELINE_DIR="$(dirname "$0")/baselines"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_FILE="$REPORT_DIR/nmap-report-${TIMESTAMP}.md"

mkdir -p "$REPORT_DIR"

echo "=== Security Infrastructure Scan - Nmap ==="
echo "Target: $SECURITY_TARGET"
echo "Timestamp: $TIMESTAMP"
echo ""

# Extract host from target
HOST=$(echo "$SECURITY_TARGET" | sed -E 's|https?://||;s|/.*||;s|:.*||')
PORTS=""
SERVICES=""
WARNINGS=0
CRITICALS=0

# Function to check if nmap is installed
check_nmap() {
    if ! command -v nmap &> /dev/null; then
        echo "ERROR: nmap is not installed"
        echo "Install with:"
        echo "  Ubuntu/Debian: sudo apt-get install nmap"
        echo "  macOS: brew install nmap"
        echo "  Windows: https://nmap.org/download.html"
        exit 1
    fi
}

# Function to run nmap scan
run_nmap() {
    local scan_type=$1
    local args=$2
    
    echo "--- Running: nmap $args ---"
    
    case $scan_type in
        "quick")
            nmap -Pn -T4 --top-ports 100 "$HOST" 2>/dev/null
            ;;
        "service")
            nmap -Pn -sV -T4 "$HOST" 2>/dev/null
            ;;
        "full")
            nmap -Pn -sV -sC -T4 --top-ports 1000 "$HOST" 2>/dev/null
            ;;
    esac
}

# Function to parse nmap output
parse_nmap_output() {
    local output=$1
    
    # Extract open ports
    OPEN_PORTS=$(echo "$output" | grep -oP '\d+(?=/tcp\s+open)' | tr '\n' ',' | sed 's/,$//')
    
    # Extract services
    SERVICES_RAW=$(echo "$output" | grep -P '\d+/tcp\s+open' | awk '{print $1, $3}')
    
    # Check for dangerous ports
    DANGEROUS_PORTS="21 22 23 3306 5432 6379 27017 8080 8081 9200 27017"
    for port in $DANGEROUS_PORTS; do
        if echo "$OPEN_PORTS" | grep -qw "$port"; then
            echo "WARNING: Dangerous port $port is open"
            ((WARNINGS++))
        fi
    done
}

# Function to generate report
generate_report() {
    local scan_output=$1
    
    cat > "$REPORT_FILE" << EOF
# Security Infrastructure Report - Nmap

**Date**: $(date)
**Target**: $SECURITY_TARGET
**Host**: $HOST

## Scan Results

### Open Ports

| Port | Service | Status |
|------|---------|--------|
EOF
    
    echo "$scan_output" | grep -P '\d+/tcp\s+open' | while read -r line; do
        port=$(echo "$line" | awk '{print $1}' | cut -d'/' -f1)
        service=$(echo "$line" | awk '{print $3}')
        echo "| $port | $service | OPEN |"
    done >> "$REPORT_FILE"
    
    cat >> "$REPORT_FILE" << EOF

### Services Detected

\`\`\`
$SERVICES_RAW
\`\`\`

### Security Assessment

- **Open Ports**: $(echo "$OPEN_PORTS" | tr ',' '\n' | wc -l)
- **Warnings**: $WARNINGS
- **Critical**: $CRITICALS

### Dangerous Ports Check

| Port | Known Risk | Status |
|------|-----------|--------|
| 21 | FTP (cleartext) | $([ $(echo "$OPEN_PORTS" | grep -cw "21") -gt 0 ] && echo "EXPOSED" || echo "OK") |
| 22 | SSH | $([ $(echo "$OPEN_PORTS" | grep -cw "22") -gt 0 ] && echo "EXPOSED" || echo "OK") |
| 23 | Telnet (cleartext) | $([ $(echo "$OPEN_PORTS" | grep -cw "23") -gt 0 ] && echo "EXPOSED" || echo "OK") |
| 3306 | MySQL | $([ $(echo "$OPEN_PORTS" | grep -cw "3306") -gt 0 ] && echo "EXPOSED" || echo "OK") |
| 5432 | PostgreSQL | $([ $(echo "$OPEN_PORTS" | grep -cw "5432") -gt 0 ] && echo "EXPOSED" || echo "OK") |
| 6379 | Redis | $([ $(echo "$OPEN_PORTS" | grep -cw "6379") -gt 0 ] && echo "EXPOSED" || echo "OK") |
| 27017 | MongoDB | $([ $(echo "$OPEN_PORTS" | grep -cw "27017") -gt 0 ] && echo "EXPOSED" || echo "OK") |
| 8080 | HTTP Alt | $([ $(echo "$OPEN_PORTS" | grep -cw "8080") -gt 0 ] && echo "EXPOSED" || echo "OK") |

### Baseline Comparison

EOF
    
    if [ -f "$BASELINE_DIR/ports-baseline.json" ]; then
        echo "Comparing with baseline..." >> "$REPORT_FILE"
        # Baseline comparison logic would go here
        echo "- Baseline file: ports-baseline.json" >> "$REPORT_FILE"
    else
        echo "- No baseline file found. Create with: \`npm run security:baseline\`" >> "$REPORT_FILE"
    fi
    
    cat >> "$REPORT_FILE" << EOF

### Recommendations

1. Close unnecessary ports
2. Use firewall rules to restrict access
3. Implement port knocking if needed
4. Regular security scans recommended

### Raw Nmap Output

\`\`\`
$scan_output
\`\`\`

---
Generated by: Security Infrastructure Scan (Phase 4)
EOF
    
    echo ""
    echo "=== Report generated: $REPORT_FILE ==="
}

# Main execution
check_nmap

echo "Phase 1: Quick scan (top 100 ports)..."
QUICK_OUTPUT=$(run_nmap "quick")
echo "$QUICK_OUTPUT"

echo ""
echo "Phase 2: Service detection..."
SERVICE_OUTPUT=$(run_nmap "service")
echo "$SERVICE_OUTPUT"

echo ""
echo "Phase 3: Parsing results..."
parse_nmap_output "$SERVICE_OUTPUT"

echo ""
echo "Phase 4: Generating report..."
generate_report "$SERVICE_OUTPUT"

echo ""
echo "=== Scan Complete ==="
echo "Report: $REPORT_FILE"
echo "Open ports: $OPEN_PORTS"
echo "Warnings: $WARNINGS"
