-- Progresso por marcos com checklist.
-- Marco = progress_steps (reaproveitado). Tarefas e historico de revisoes sao tabelas novas.
-- Significado de status: PENDING nao iniciado, ACTIVE em andamento, DONE aprovado, REJECTED devolvido.
-- submitted_at preenchido = marco enviado pelo aluno aguardando decisao do orientador.
-- O peso deixa de participar do calculo; a coluna e mantida por compatibilidade.

ALTER TABLE progress_steps ADD COLUMN submitted_at TIMESTAMP;
ALTER TABLE progress_steps ALTER COLUMN weight SET DEFAULT 0;

CREATE TABLE progress_step_tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id INTEGER NOT NULL REFERENCES progress_steps(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    required BOOLEAN NOT NULL DEFAULT FALSE,
    origin VARCHAR(20) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    completed_by INTEGER REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    task_order INTEGER NOT NULL,
    created_by INTEGER REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    created_at TIMESTAMP,
    CONSTRAINT ck_progress_step_tasks_origin CHECK (origin IN ('ORIENTADOR', 'ALUNO'))
);
CREATE INDEX idx_progress_step_tasks_step ON progress_step_tasks(step_id, task_order);

CREATE TABLE progress_step_reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id INTEGER NOT NULL REFERENCES progress_steps(id) ON DELETE CASCADE,
    action VARCHAR(20) NOT NULL,
    comment TEXT,
    author_id INTEGER REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_progress_step_reviews_action CHECK (action IN ('ENVIADO', 'APROVADO', 'DEVOLVIDO'))
);
CREATE INDEX idx_progress_step_reviews_step ON progress_step_reviews(step_id, created_at);

-- Preserva os dados: cada marco existente ganha 1 tarefa com o titulo do marco
-- (concluida se o marco estava DONE, pendente nos demais).
INSERT INTO progress_step_tasks (step_id, title, required, origin, completed, completed_at, completed_by, task_order, created_at)
SELECT id, title, FALSE, 'ORIENTADOR',
       CASE WHEN status = 'DONE' THEN TRUE ELSE FALSE END,
       CASE WHEN status = 'DONE' THEN COALESCE(completed_at, created_at, CURRENT_TIMESTAMP) ELSE NULL END,
       CASE WHEN status = 'DONE' THEN completed_by ELSE NULL END,
       1,
       COALESCE(created_at, CURRENT_TIMESTAMP)
FROM progress_steps;

-- Marcos ja aprovados entram no historico como aprovacao.
INSERT INTO progress_step_reviews (step_id, action, comment, author_id, created_at)
SELECT id, 'APROVADO', NULL, completed_by, COALESCE(completed_at, created_at, CURRENT_TIMESTAMP)
FROM progress_steps
WHERE status = 'DONE';

-- Antes ACTIVE era "a etapa da vez" (apenas uma por projeto); agora significa ao menos 1 item concluido.
UPDATE progress_steps SET status = 'PENDING' WHERE status = 'ACTIVE';
