-- Conservative baseline of the schema managed by the current JPA model.
-- Existing production databases are baselined at version 1 and do not execute this file.
CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL, tipo VARCHAR(30) NOT NULL,
    data_cadastro TIMESTAMP, ativo BOOLEAN, instituicao VARCHAR(150), bio TEXT,
    foto_perfil_url VARCHAR(500), tema VARCHAR(30), notificacoes_ativas BOOLEAN
);
CREATE TABLE curso (id_curso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(100) NOT NULL);
CREATE TABLE area_pesquisa (id_area INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(100) NOT NULL, id_curso INTEGER REFERENCES curso(id_curso));
CREATE TABLE aluno (id_aluno INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_usuario INTEGER NOT NULL UNIQUE REFERENCES usuario(id_usuario) ON DELETE CASCADE, ra VARCHAR(20) NOT NULL UNIQUE, semestre INTEGER, interesses TEXT, id_curso INTEGER REFERENCES curso(id_curso));
CREATE TABLE orientador (id_orientador INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_usuario INTEGER NOT NULL UNIQUE REFERENCES usuario(id_usuario) ON DELETE CASCADE, departamento VARCHAR(100) NOT NULL, titulacao VARCHAR(50) NOT NULL);
CREATE TABLE projeto (
    id_projeto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL, descricao TEXT, requisitos TEXT, tecnologias TEXT, vagas INTEGER,
    status VARCHAR(40) NOT NULL, data_criacao TIMESTAMP, data_inicio DATE, data_fim DATE,
    data_limite_inscricao DATE, id_area INTEGER REFERENCES area_pesquisa(id_area),
    id_orientador INTEGER REFERENCES orientador(id_orientador) ON DELETE CASCADE,
    id_aluno_criador INTEGER REFERENCES aluno(id_aluno) ON DELETE CASCADE
);
CREATE TABLE inscricao (
    id_inscricao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aluno INTEGER NOT NULL REFERENCES aluno(id_aluno) ON DELETE CASCADE,
    id_projeto INTEGER NOT NULL REFERENCES projeto(id_projeto) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL, motivacao TEXT, parecer_orientador TEXT, data_inscricao TIMESTAMP,
    CONSTRAINT uk_inscricao_aluno_projeto UNIQUE (id_aluno, id_projeto)
);
CREATE TABLE progress_steps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projeto(id_projeto) ON DELETE CASCADE,
    title VARCHAR(120) NOT NULL, description TEXT, weight INTEGER NOT NULL,
    step_order INTEGER NOT NULL, status VARCHAR(20) NOT NULL, completed_at TIMESTAMP,
    completed_by INTEGER REFERENCES usuario(id_usuario) ON DELETE SET NULL, created_at TIMESTAMP
);
CREATE TABLE progresso (
    id_progresso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_projeto INTEGER NOT NULL REFERENCES projeto(id_projeto) ON DELETE CASCADE,
    id_usuario_autor INTEGER REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    titulo VARCHAR(150), tipo VARCHAR(30) NOT NULL, fase VARCHAR(100), descricao TEXT,
    metadata_json TEXT, categoria VARCHAR(30), id_etapa INTEGER REFERENCES progress_steps(id),
    step_contribution INTEGER, data_registro TIMESTAMP
);
CREATE TABLE documento (
    id_documento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    tipo VARCHAR(40) NOT NULL, status VARCHAR(40) NOT NULL, observacao_status TEXT,
    caminho VARCHAR(1000) NOT NULL, nome_arquivo VARCHAR(255), data_envio TIMESTAMP
);
CREATE TABLE feedback (
    id_feedback INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nota INTEGER NOT NULL,
    comentario TEXT, id_projeto INTEGER NOT NULL REFERENCES projeto(id_projeto) ON DELETE CASCADE,
    id_usuario_avaliador INTEGER NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    data_feedback TIMESTAMP, CONSTRAINT uk_feedback_projeto_avaliador UNIQUE (id_projeto, id_usuario_avaliador)
);
CREATE TABLE notificacao (
    id_notificacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    mensagem TEXT NOT NULL, tipo VARCHAR(50) NOT NULL, entidade_relacionada VARCHAR(50),
    id_entidade_relacionada INTEGER, rota_sugerida VARCHAR(255), payload_resumo TEXT,
    lida BOOLEAN, data_criacao TIMESTAMP
);
CREATE TABLE conversa (id_conversa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_projeto INTEGER REFERENCES projeto(id_projeto) ON DELETE CASCADE, tipo VARCHAR(30) NOT NULL, data_criacao TIMESTAMP WITH TIME ZONE);
CREATE TABLE conversa_participantes (id_conversa INTEGER NOT NULL REFERENCES conversa(id_conversa) ON DELETE CASCADE, id_usuario INTEGER NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE, PRIMARY KEY (id_conversa, id_usuario));
CREATE TABLE mensagem (id_mensagem INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_conversa INTEGER NOT NULL REFERENCES conversa(id_conversa) ON DELETE CASCADE, id_remetente INTEGER NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE, conteudo TEXT NOT NULL, data_envio TIMESTAMP WITH TIME ZONE, editada BOOLEAN NOT NULL, data_edicao TIMESTAMP WITH TIME ZONE);
CREATE TABLE configuracao_sistema (id_configuracao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chave VARCHAR(80) NOT NULL UNIQUE, valor VARCHAR(500) NOT NULL, descricao VARCHAR(200), atualizado_em TIMESTAMP NOT NULL);
CREATE TABLE auditoria_evento (id_auditoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_admin INTEGER NOT NULL REFERENCES usuario(id_usuario), acao VARCHAR(60) NOT NULL, recurso VARCHAR(60) NOT NULL, id_recurso INTEGER, descricao VARCHAR(300), data_evento TIMESTAMP NOT NULL);
