ALTER TABLE progress_steps ADD COLUMN due_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE progress_steps ADD COLUMN responsible VARCHAR(20) NOT NULL DEFAULT 'AMBOS';
ALTER TABLE progress_steps ADD COLUMN required BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE progress_steps ADD CONSTRAINT ck_progress_steps_responsible CHECK (responsible IN ('ALUNO', 'ORIENTADOR', 'AMBOS'));

CREATE TABLE project_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projeto(id_projeto) ON DELETE CASCADE,
    step_id INTEGER REFERENCES progress_steps(id) ON DELETE SET NULL,
    author_user_id INTEGER NOT NULL REFERENCES usuario(id_usuario),
    title VARCHAR(180) NOT NULL, category VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_project_deliveries_status CHECK (status IN ('PENDING_REVIEW', 'CHANGES_REQUESTED', 'APPROVED'))
);
CREATE TABLE delivery_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id BIGINT NOT NULL REFERENCES project_deliveries(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL, storage_path VARCHAR(1000) NOT NULL,
    file_name VARCHAR(255) NOT NULL, content_type VARCHAR(120), size_bytes BIGINT,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_delivery_version UNIQUE (delivery_id, version_number),
    CONSTRAINT ck_delivery_version_number CHECK (version_number > 0),
    CONSTRAINT ck_delivery_size CHECK (size_bytes IS NULL OR size_bytes >= 0)
);
CREATE TABLE delivery_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_version_id BIGINT NOT NULL UNIQUE REFERENCES delivery_versions(id) ON DELETE CASCADE,
    reviewer_user_id INTEGER NOT NULL REFERENCES usuario(id_usuario),
    decision VARCHAR(30) NOT NULL, comment VARCHAR(2000),
    reviewed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_delivery_review_decision CHECK (decision IN ('CHANGES_REQUESTED', 'APPROVED')),
    CONSTRAINT ck_delivery_review_comment CHECK (decision <> 'CHANGES_REQUESTED' OR NULLIF(TRIM(comment), '') IS NOT NULL)
);
CREATE TABLE academic_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projeto(id_projeto) ON DELETE CASCADE,
    step_id INTEGER NOT NULL REFERENCES progress_steps(id) ON DELETE CASCADE,
    student_id INTEGER NOT NULL REFERENCES aluno(id_aluno), advisor_id INTEGER NOT NULL REFERENCES orientador(id_orientador),
    participation SMALLINT NOT NULL, technical_quality SMALLINT NOT NULL,
    deadline_compliance SMALLINT NOT NULL, communication SMALLINT NOT NULL,
    advisor_comment VARCHAR(2000) NOT NULL, average_score NUMERIC(3,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_academic_evaluation UNIQUE (student_id, project_id, step_id),
    CONSTRAINT ck_academic_scores CHECK (participation BETWEEN 1 AND 5 AND technical_quality BETWEEN 1 AND 5 AND deadline_compliance BETWEEN 1 AND 5 AND communication BETWEEN 1 AND 5),
    CONSTRAINT ck_academic_average CHECK (average_score BETWEEN 1 AND 5),
    CONSTRAINT ck_academic_comment CHECK (NULLIF(TRIM(advisor_comment), '') IS NOT NULL)
);
CREATE TABLE academic_evaluation_acknowledgements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT NOT NULL UNIQUE REFERENCES academic_evaluations(id) ON DELETE CASCADE,
    student_user_id INTEGER NOT NULL REFERENCES usuario(id_usuario), student_comment VARCHAR(2000),
    acknowledged_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE deadline_notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id INTEGER NOT NULL REFERENCES progress_steps(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    notification_kind VARCHAR(20) NOT NULL, reference_date DATE NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_deadline_notification UNIQUE (step_id, user_id, notification_kind, reference_date),
    CONSTRAINT ck_deadline_notification_kind CHECK (notification_kind IN ('DAYS_7', 'DAYS_3', 'DAYS_1', 'OVERDUE'))
);

CREATE INDEX idx_projeto_orientador_status ON projeto(id_orientador, status);
CREATE INDEX idx_inscricao_projeto_status ON inscricao(id_projeto, status);
CREATE INDEX idx_progress_steps_due ON progress_steps(status, due_at);
CREATE INDEX idx_project_deliveries_project_status ON project_deliveries(project_id, status);
CREATE INDEX idx_delivery_versions_delivery ON delivery_versions(delivery_id, version_number DESC);
CREATE INDEX idx_project_deliveries_step ON project_deliveries(step_id);
CREATE INDEX idx_project_deliveries_author ON project_deliveries(author_user_id);
CREATE INDEX idx_delivery_reviews_reviewer ON delivery_reviews(reviewer_user_id);
CREATE INDEX idx_academic_evaluations_advisor ON academic_evaluations(advisor_id, project_id);
CREATE INDEX idx_academic_evaluations_student ON academic_evaluations(student_id, project_id);
CREATE INDEX idx_academic_evaluations_project_step ON academic_evaluations(project_id, step_id);
CREATE INDEX idx_documento_usuario_tipo ON documento(id_usuario, tipo);
CREATE INDEX idx_deadline_notification_sent ON deadline_notification_log(reference_date, notification_kind);
CREATE INDEX idx_academic_ack_student ON academic_evaluation_acknowledgements(student_user_id);
CREATE INDEX idx_deadline_notification_user ON deadline_notification_log(user_id, reference_date);
