// Opções pré-definidas usadas tanto no cadastro quanto na edição de perfil,
// para manter os valores consistentes (evita texto livre divergente).

export const INSTITUICOES = [
  "Universidade de Sao Paulo (USP)",
  "Universidade Estadual de Sao Paulo (UNESP)",
  "Universidade Estadual de Campinas (UNICAMP)",
  "Universidade Federal de Sao Paulo (UNIFESP)",
  "Universidade Federal de Minas Gerais (UFMG)",
  "Universidade Federal do Rio de Janeiro (UFRJ)",
  "Universidade Federal do Rio Grande do Sul (UFRGS)",
  "Universidade Federal de Santa Catarina (UFSC)",
  "Universidade Federal do Parana (UFPR)",
  "Universidade Federal de Pernambuco (UFPE)",
  "Universidade Federal da Bahia (UFBA)",
  "Universidade de Brasilia (UnB)",
  "Universidade Federal de Sao Carlos (UFSCar)",
  "Universidade Federal do ABC (UFABC)",
  "Pontificia Universidade Catolica de Sao Paulo (PUC-SP)",
  "Pontificia Universidade Catolica do Rio de Janeiro (PUC-Rio)",
  "Pontificia Universidade Catolica de Minas Gerais (PUC Minas)",
  "Universidade Presbiteriana Mackenzie",
  "Fundacao Getulio Vargas (FGV)",
  "Instituto Federal de Sao Paulo (IFSP)",
  "Instituto Federal do Rio de Janeiro (IFRJ)",
  "Centro Universitario Senac",
  "Outra",
];

export const TITULACOES = ["Especialista", "Mestre", "Doutor", "Pos-doutor"];

export const DEPARTAMENTOS = [
  "Ciencia da Computacao",
  "Engenharia de Software",
  "Engenharia Eletrica",
  "Engenharia Mecanica",
  "Engenharia Civil",
  "Engenharia de Producao",
  "Matematica",
  "Fisica",
  "Quimica",
  "Biologia",
  "Administracao",
  "Economia",
  "Direito",
  "Psicologia",
  "Medicina",
  "Enfermagem",
  "Arquitetura e Urbanismo",
  "Design",
  "Comunicacao Social",
  "Educacao",
  "Outro",
];
